displayName: JWT And OPA Access Management
type: middleware

import: github.com/traefik-plugins/traefik-jwt-plugin

summary: Checks JWT tokens for required fields. Supports Open Policy Agent (OPA) and signature validation with JWKS.

iconPath: jwt.png

testData:
  OpaUrl: http://localhost:8181/v1/data/example
  OpaAllowField: allow
  OpaBody: true
  PayloadFields:
    - exp
  Required: true
  Keys:
    - |
      -----BEGIN PUBLIC KEY-----
      MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAnzyis1ZjfNB0bBgKFMSv
      vkTtwlvBsaJq7S5wA+kzeVOVpVWwkWdVha4s38XM/pa/yr47av7+z3VTmvDRyAHc
      aT92whREFpLv9cj5lTeJSibyr/Mrm/YtjCZVWgaOYIhwrXwKLqPr/11inWsAkfIy
      tvHWTxZYEcXLgAXFuUuaS3uF9gEiNQwzGTU1v0FqkqTBr4B8nW3HCN47XUu0t8Y0
      e+lf4s4OxQawWD79J9/5d3Ry0vbV3Am1FtGJiJvOwRsIfVChDpYStTcHTCMqtvWb
      V6L11BWkpzGXSW4Hv43qa+GSYOD2QU68Mb59oSk2OB+BtOLpJofmbGEGgvmwyCI9
      MwIDAQAB
      -----END PUBLIC KEY-----
  OpaHeaders:
    X-Allowed: allow
  JwtHeaders:
    X-Subject: sub
  OpaResponseHeaders:
    X-Allowed: allow
  OpaHttpStatusField: allow_status_code
